CREATE TABLE public.articles (
                                 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 url character varying(512) NOT NULL UNIQUE,
                                 title text,
                                 content text,
                                 comments text,
                                 created_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.articles IS '스크래핑된 네이버 카페 게시글';