-- beauty_promo_posts 테이블 생성
CREATE TABLE public.beauty_promo_posts (
                                           id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                           created_at timestamp with time zone NOT NULL DEFAULT now(),
                                           url character varying(512) NOT NULL,
                                           title text NOT NULL,
                                           content text NOT NULL,
                                           comments text,
                                           CONSTRAINT beauty_promo_posts_pkey PRIMARY KEY (id),
                                           CONSTRAINT beauty_promo_posts_url_key UNIQUE (url)
);

-- 테이블에 대한 RLS(Row Level Security) 활성화
ALTER TABLE public.beauty_promo_posts ENABLE ROW LEVEL SECURITY;

-- 서비스 키를 사용하는 요청에 대해 모든 작업 허용 정책 생성
CREATE POLICY "Enable full access for service_role"
ON public.beauty_promo_posts
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- 모든 사용자가 데이터를 읽을 수 있도록 허용
CREATE POLICY "Enable read access for all users"
ON public.beauty_promo_posts
FOR SELECT
                      USING (true);