-- "countries" 테이블을 생성합니다.
-- 이 테이블은 국가의 이름과 같은 기본 정보를 저장합니다.
create table public.countries (
    -- 'id'는 각 행을 고유하게 식별하는 기본 키입니다. 자동으로 증가합니다.
                                  id bigint generated by default as identity primary key,

    -- 'name'은 국가의 이름을 저장하는 텍스트 필드입니다. 비어 있을 수 없습니다.
                                  name text not null,

    -- 'created_at'은 행이 생성된 시간을 자동으로 기록합니다.
                                  created_at timestamp with time zone not null default now()
);

-- 테이블에 대한 RLS(Row Level Security)를 활성화합니다.
-- 이것은 Supabase 보안의 핵심이며, 기본적으로 모든 접근을 차단합니다.
alter table public.countries enable row level security;

-- 모든 사용자가 "countries" 테이블의 데이터를 읽을(select) 수 있도록 허용하는 정책을 생성합니다.
-- 'using (true)'는 조건 없이 모든 행에 대해 이 정책이 적용됨을 의미합니다.
create policy "Enable read access for all users"
on public.countries for select
                                   using (true);